"""image cascade delete embedding

Revision ID: 4c63b3dba5dc
Revises: dcbe29b7326e
Create Date: 2024-12-27 21:43:04.604085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4c63b3dba5dc'
down_revision: Union[str, None] = 'dcbe29b7326e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clipembedding', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('clipembedding_image_id_fkey', 'clipembedding', type_='foreignkey')
    op.create_foreign_key(None, 'clipembedding', 'image', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clipembedding', type_='foreignkey')
    op.create_foreign_key('clipembedding_image_id_fkey', 'clipembedding', 'image', ['image_id'], ['id'])
    op.alter_column('clipembedding', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
