services:
  db:
    restart: "no"
    ports:
      - "5432:5432"

  api:
    restart: "no"
    ports:
      - "8000:8000"
    command: sleep infinity # for dev, infinite loop to keep container alive doing nothing
    develop:
      watch:
        - path: .
          action: sync
          target: /app
        - path: ./pyproject.toml
          action: rebuild
    volumes:
      - ./static:/app/static

  prestart:
    restart: "no"
    develop:
      watch:
        - path: .
          action: sync
          target: /app
        - path: ./pyproject.toml
          action: rebuild
